---
# LEAF4 specific data model

# Interfaces
interfaces:
  Ethernet1:
    descr: "To_Spine1"
    mode: "trunk"
  Ethernet2:
    descr: "To_Spine2"
    mode: "trunk"
  Ethernet48:
    descr: "To_Leaf3"
    mode: "trunk"

# VLANs
vlans:
  - id: 20
    name: "twenty"